name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: "./compose.yml"
          service: app
          command: "./ci.sh"
